/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'add-user-email': RouteRecordInfo<'add-user-email', '/add-user-email', Record<never, never>, Record<never, never>>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-account': RouteRecordInfo<'admin-account', '/admin/account', Record<never, never>, Record<never, never>>,
    'admin-admins': RouteRecordInfo<'admin-admins', '/admin/admins', Record<never, never>, Record<never, never>>,
    'admin-admins-id': RouteRecordInfo<'admin-admins-id', '/admin/admins/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-admins-add-admin': RouteRecordInfo<'admin-admins-add-admin', '/admin/admins/add-admin', Record<never, never>, Record<never, never>>,
    'admin-agents': RouteRecordInfo<'admin-agents', '/admin/agents', Record<never, never>, Record<never, never>>,
    'admin-agents-id': RouteRecordInfo<'admin-agents-id', '/admin/agents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-agents-add-agent': RouteRecordInfo<'admin-agents-add-agent', '/admin/agents/add-agent', Record<never, never>, Record<never, never>>,
    'admin-clients': RouteRecordInfo<'admin-clients', '/admin/clients', Record<never, never>, Record<never, never>>,
    'admin-clients-id': RouteRecordInfo<'admin-clients-id', '/admin/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-clients-add-client': RouteRecordInfo<'admin-clients-add-client', '/admin/clients/add-client', Record<never, never>, Record<never, never>>,
    'admin-invoices': RouteRecordInfo<'admin-invoices', '/admin/invoices', Record<never, never>, Record<never, never>>,
    'admin-invoices-id': RouteRecordInfo<'admin-invoices-id', '/admin/invoices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-invoices-add-invoice': RouteRecordInfo<'admin-invoices-add-invoice', '/admin/invoices/add-invoice', Record<never, never>, Record<never, never>>,
    'admin-invoices-edit-id': RouteRecordInfo<'admin-invoices-edit-id', '/admin/invoices/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-invoices-preview-id': RouteRecordInfo<'admin-invoices-preview-id', '/admin/invoices/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-notifications-reminders': RouteRecordInfo<'admin-notifications-reminders', '/admin/notifications-reminders', Record<never, never>, Record<never, never>>,
    'admin-preferences': RouteRecordInfo<'admin-preferences', '/admin/preferences', Record<never, never>, Record<never, never>>,
    'admin-reports-tab': RouteRecordInfo<'admin-reports-tab', '/admin/reports/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'agent': RouteRecordInfo<'agent', '/agent', Record<never, never>, Record<never, never>>,
    'agent-account': RouteRecordInfo<'agent-account', '/agent/account', Record<never, never>, Record<never, never>>,
    'agent-alarm-alerts': RouteRecordInfo<'agent-alarm-alerts', '/agent/alarm-alerts', Record<never, never>, Record<never, never>>,
    'agent-preferences': RouteRecordInfo<'agent-preferences', '/agent/preferences', Record<never, never>, Record<never, never>>,
    'checkpoint': RouteRecordInfo<'checkpoint', '/checkpoint', Record<never, never>, Record<never, never>>,
    'client': RouteRecordInfo<'client', '/client', Record<never, never>, Record<never, never>>,
    'client-account': RouteRecordInfo<'client-account', '/client/account', Record<never, never>, Record<never, never>>,
    'client-alarm-alerts': RouteRecordInfo<'client-alarm-alerts', '/client/alarm-alerts', Record<never, never>, Record<never, never>>,
    'client-alarm-alerts-details-id': RouteRecordInfo<'client-alarm-alerts-details-id', '/client/alarm-alerts/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'client-domains': RouteRecordInfo<'client-domains', '/client/domains', Record<never, never>, Record<never, never>>,
    'client-domains-id': RouteRecordInfo<'client-domains-id', '/client/domains/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'client-domains-add-domain': RouteRecordInfo<'client-domains-add-domain', '/client/domains/add-domain', Record<never, never>, Record<never, never>>,
    'client-domains-management-tab': RouteRecordInfo<'client-domains-management-tab', '/client/domains/management/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'client-invoice-id': RouteRecordInfo<'client-invoice-id', '/client/invoice/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'client-invoice-change-plan-id': RouteRecordInfo<'client-invoice-change-plan-id', '/client/invoice/change-plan/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'client-invoice-pay-now-id': RouteRecordInfo<'client-invoice-pay-now-id', '/client/invoice/pay-now/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'client-plans-billing': RouteRecordInfo<'client-plans-billing', '/client/plans-billing', Record<never, never>, Record<never, never>>,
    'client-preferences': RouteRecordInfo<'client-preferences', '/client/preferences', Record<never, never>, Record<never, never>>,
    'client-pricing': RouteRecordInfo<'client-pricing', '/client/pricing', Record<never, never>, Record<never, never>>,
    'client-register-success': RouteRecordInfo<'client-register-success', '/client/register-success', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'register-success': RouteRecordInfo<'register-success', '/register-success', Record<never, never>, Record<never, never>>,
    'reset-forgot-password': RouteRecordInfo<'reset-forgot-password', '/reset/forgot-password', Record<never, never>, Record<never, never>>,
    'reset-password-token': RouteRecordInfo<'reset-password-token', '/reset/password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'reset-verify-email': RouteRecordInfo<'reset-verify-email', '/reset/verify-email', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
